### ISSUE TITLE
Very hard to install

### ISSUE THREAD

**Issue by MatMoul** [MohamadSaada/LogiGSK#1]
I just tried to install but it's rather complicated.
It would be cool to have an installation script ...
I test it in VM, if script is not fully tested, make a branch for testing

**Comment by MohamadSaada** [comment]
Hi, I've provided linux packages that will take care of the installation process, and later today i will provide a script that will compile the code and install everything automatically, hope this takes care of the problem.

**Comment by MohamadSaada** [comment]
I have provided two scripts , the first script `logigsk-buildpackage` will compile the source and create a deb or rpm package, which can be installed through the package manager. the second script `INSTALL` compiles the source and installs the program directly without the need to create a package. I would advise to use the first one, but both work very well, please try them and let me know what you think.

**Comment by MatMoul** [comment]
Sorry for my late reply, too much job :-(
But it's cool to have provided these scripts, I try this weekend

**Comment by MatMoul** [comment]
Installer work well on KDE Neon...
Just tested with G810 and my keyboard is detected and seem work...

**Comment by MohamadSaada** [comment]
Glad that it worked for you, really appreciate the time and effort you've put into trying it, I hope you don't mind that I've add your name to two of the classes that I've converted from your project, along with a link to your project's website.

**Comment by MatMoul** [comment]
With pleasure...
It would also be nice to add a license file...
[https://github.com/MatMoul/g810-led/blob/master/LICENSE](https://github.com/MatMoul/g810-led/blob/master/LICENSE)

**Comment by MohamadSaada** [comment]
I have followed your recommendation and added a LICENCE file. Each single source file has a preamble which mentions the licence and the script creates a licence file in /usr/share/doc/logigsk.

I will follow your project and make amendments accordingly.
