### ISSUE TITLE
Having issues getting it working

### ISSUE THREAD

**Issue by coreybruce** [MohamadSaada/LogiGSK#12]
System: Xubuntu 16.04 LTS

I need some help on getting this working, I've installed it but the service wont start even tho I started it and I got a error saying 

Starting the LogiGSK service...
Cannot locate Java Home
The LogiGSK service has started.

tho I did 

export JAVA_HOME=/usr/lib/jvm/jre-8-oracle-x64

really wish this was just a install and use instead of this unneeded complications..

**Comment by coreybruce** [comment]
Don't worry I got it working, had to manually add my java location in the script and reboot tho it says the service hasn't started..

thanks! 

hope it gets a little less complicated for especially new users :D

**Comment by MohamadSaada** [comment]
@coreybruce glad that you have solved it by yourself. Sorry about it being a little complicated, it is still a work in progress. If the service is not running automatically check the **Service not starting automatically?** Section in the main page. Make sure that your service is running as it loads the profile automatically on login and resume. Cheers

**Comment by coreybruce** [comment]
Ahh I see well good work and cheers!
