### ISSUE TITLE
Add request for Turkish Q layout

### ISSUE THREAD

**Issue by Alpkant** [MohamadSaada/LogiGSK#18]
If you can add Turkish Q keyboard layout it would be awesome.

**Comment by MohamadSaada** [comment]
@Alpkant Hi, can you send me a clean large res image of your keyboard on a white background? I can't find any online, thanks, Cheers.

**Comment by MohamadSaada** [comment]
Closed due to no further communication from the user.

**Comment by Alpkant** [comment]
I am really sorry for my late reply but i didn't get or couldn't see the notification of your comments. https://imgur.com/N692JQH is this image good for you or should i take another image ?

**Comment by MohamadSaada** [comment]
Hi, thanks for the image, but if you can take a higher resolution one that would be great and preferably without flash effects visible on it, and with the keyboard lights off please. Thanks.

**Comment by Alpkant** [comment]
I am not able to take higher resolution but i can take without flash and lights off if you want.

**Comment by Alpkant** [comment]
Here is another try https://ibb.co/b7HMG9
