### ISSUE TITLE
Big "This-can't-be-right"

### ISSUE THREAD

**Issue by SammyKat** [MohamadSaada/LogiGSK#19]
Hi,
0

root@lk-ws:/home/sammy/leds/LogiGSK# ./INSTALL 
This program requires java but it's not installed. Aborting.
This program requires javac but it's not installed. Aborting.
This program requires jsvc but it's not installed. Aborting.
This program requires ant but it's not installed. Aborting.
compiling the project using Apache Ant
./INSTALL: line 25: ant: command not found
cp: cannot stat '/home/sammy/leds/LogiGSK/dist/LogiGSK.jar': No such file or directory
chmod: cannot access '/usr/share/logigsk/LogiGSK.jar': No such file or directory
cp: cannot stat '/home/sammy/leds/LogiGSK/dist/lib/*.jar': No such file or directory
chmod: cannot access '/usr/share/logigsk/lib/*.jar': No such file or directory
failed to setup LogiGSK service startup file in autostart, please refere to website for more details.
LogiGSK has been successfully installed

There's something fundamentally wrong with this picture.... specially considering the last line :-)

**Comment by MohamadSaada** [comment]
@SammyKat there is something fundamentally wrong with this picture as the script shouldn't go pass the first few checks. The script usually checks for needed dependencies. If all are satisfied it continues running, if all or any isn't satisfied, then it should stop running.

Do you have all the needed dependencies (Java, jsvc, ant, etc...)installed? Did you run the installer as root? Please let me know. Cheers.

**Comment by MohamadSaada** [comment]
Closed due to no further communication from user.
