### ISSUE TITLE
G-Keys input not working?

### ISSUE THREAD

**Issue by meliorisse** [MohamadSaada/LogiGSK#2]
It seems that the G-keys for the G910 keyboard are not working on Ubuntu 16.04. The G-Key pane in the application is blank. Output in xev (both sudo and non-sudo) shows no output/input at all from these keys. 

The LEDs do control just fine, though!

(also, excellent program! - I was able to build successfully and install.)

**Comment by MohamadSaada** [comment]
Hi, I'm sorry for the late reply, the program doesn't support the G-Keys yet, hopefully it will come on a later date. but I'm really busy during the next two months so don't expect anything anytime soon​ :-(

**Comment by Mela** [comment]
G-Key support would be really important. Please add.

**Comment by wraith3690** [comment]
I have just run into this  https://github.com/JSubelj/g910-gkey-macro-support 
it adds G-key support maybe you could use this? I do not know if it will work for other keyboards but worth a look
