### ISSUE TITLE
Start the deamon and load a Proflie in CLI

### ISSUE THREAD

**Issue by boscho87** [MohamadSaada/LogiGSK#21]
Its possible to add a script in .bashrc/.bash_profile, to force it @startup because my windows (dualboot) changes the setting after start

**Comment by holzfuss** [comment]
I also have a dualboot system, but Windows does not change the Ubuntu settings.

**Comment by boscho87** [comment]
did you install the driver on windows ?

**Comment by holzfuss** [comment]
I use the "Logitech Gaming Software" on Windows.
