### ISSUE TITLE
Cannot find amy VM in Jaca Home

### ISSUE THREAD

**Issue by kemindo** [MohamadSaada/LogiGSK#24]
kemi@HeavyTuned:/usr/share/logigsk$ java --version
openjdk 10.0.1 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 10.0.1+10-Ubuntu-3ubuntu1, mixed mode)

kemi@HeavyTuned:/usr/share/logigsk$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"

kemi@HeavyTuned:/usr/share/logigsk$ ./LogiGSK start
Starting the LogiGSK service...
Cannot find any VM in Java Home /usr/lib/jvm/default-java
The LogiGSK service has started.

**Comment by kemindo** [comment]
BUILD SUCCESSFUL
Total time: 4 seconds
Daemon not running, no action taken
failed to setup LogiGSK service startup file in autostart, please refere to website for more details.
Starting the LogiGSK service...
Cannot find any VM in Java Home /usr/lib/jvm/default-java
The LogiGSK service has started.
LogiGSK has been successfully installed

**Comment by kemindo** [comment]
dont know why but it works with my G910

**Comment by andrakis** [comment]
The error message `Cannot find any VM ...` is something I just found a solution to. See #28 for my solution and if that helps you.

**Comment by MohamadSaada** [comment]
Solved by @andrakis. Thanks.
