### ISSUE TITLE
Add to AUR

### ISSUE THREAD

**Issue by ShayBox** [MohamadSaada/LogiGSK#25]
Would be really helpful if someone could add this to the AUR, I'm not really sure how to do that.

**Comment by WalterLuigi** [comment]
If I can get the software running fully on my machine, I'll look into making a package for the AUR.

**Comment by MohamadSaada** [comment]
@ShayBox I will try and do that soon.

@NullOtoko if you can do it, that will be great, and if I do it I'll let you know.

**Comment by ShayBox** [comment]
Any update on this?

**Comment by ShayBox** [comment]
It's been 1/3 of a year... any update on this?

**Comment by gchamon** [comment]
to get it running it needs `ant` package installed and after running `./INSTALL` I needed to manually create `$HOME/.local/share/LogiGSK/`. Steps are simple but I have no idea how to translate that into a working `PKGBUILD`
it really is a shame the program was written in Java. It would be way easier to make a pkg for Python

**Comment by D1Ck3n** [comment]
I am also interested in an AUR or Arch Package

**Comment by ShayBox** [comment]
Closing issue, clearly not happening
