### ISSUE TITLE
Hard-coded java home location

### ISSUE THREAD

**Issue by meliorisse** [MohamadSaada/LogiGSK#3]
After compiling via instructions and installing, I found that the program did not pick up the globally set JAVA_HOME variable. Instead, it seems to be hard coded to /usr/lib/jvm/default-java . I had to create a symbolic link via the following command:

`sudo ln -s $JAVA_HOME /usr/lib/jvm/default-java`

**Comment by MohamadSaada** [comment]
Hi, I will fix this soon, thanks for letting me know.

**Comment by MohamadSaada** [comment]
@puargs, I've commented out the statements where the variable was altered. Please try the new version and let me know, thanks.
