### ISSUE TITLE
Ubunutu 18.04 Appears to break this!

### ISSUE THREAD

**Issue by Darksaint08** [MohamadSaada/LogiGSK#30]
After upgrading to 18.04 from 17.04 I get this message when trying to start the service:

```
Starting the LogiGSK service...
Cannot find any VM in Java Home /usr/lib/jvm/default-java
The LogiGSK service has started
```

I also tried to build the deb again and this line appears to break the build as it now returns nothing:

```
USER=`who | grep ':0' | grep -o '^\w*' | head -n1`
```

when this runs the `USER` variable remains empty which causes the package build to fail.

**Comment by andrakis** [comment]
I ran into this issue myself, and found a workaround in #28 . Seems to affect the current 18.x release of all Ubuntu and derivatives.

Note that it appears to be an issue with the `jsvc` program, not LogiGSK itself. It's just that LogiGSK uses `jsvc` as a standard way to launch daemon programs in java. This likely affects all programs that use `jsvc` to provide daemon management.

**Comment by Darksaint08** [comment]
Fantastic work! Thanks! I will make a separate issue about the package builder.
