### ISSUE TITLE
Ubuntu 14.04 and G910

### ISSUE THREAD

**Issue by EricBergeron** [MohamadSaada/LogiGSK#8]
Hello Mohamad,

First and foremost, thank you very much for doing what Logitech refuses to do, which is to help us enjoy what should be a great product.  
I have the G910, everything works well in windows, I can get the LED setting to stick in Ubuntu if I close Lcore process before rebooting, If I don’t well I get the supra annoying rainbow effect when I want to work in Ubuntu which I use for my work.
I have installed LogiGSK, by downloading .deb, and having Ubuntu software centre install. have the app's Icon in bash.  Howevber when I start it, nothing happens, no GUI or anything else, no error message either.

I'm pretty sure the issue is here and not with your software.  Any idea of what I could do to at least jam the rainbow and get a minimal backlight working, any color at this point would make me happy!
could I be missing some repository component?

Again, thank you very much for your time and efforts!

Eric Bergeron

**Comment by EricBergeron** [comment]
Hello Again!!

sorry for the trouble, turns out my java was not version 8 , installed 8, rebooted and it works like a charm!
puts those logitech people to shame !  

Again a million thanks!

**Comment by MohamadSaada** [comment]
@EricBergeron  Glad to see that the issue has been solved. I have a G910 myself and this program should work fine with the G910. It's a real shame that Logitech don't want to support Linux. I want to write an extension app on android that allows the control of the keyboard through the app, but unfortunately I don't have much free time, maybe in the near future.

**Comment by EricBergeron** [comment]
Thank you again, 
how can we force a profile load on boot?  
When leaving windows, Lcore sends a "do the rainbow dance" signal, as Ubuntu reboots it is stuck with the rainbow, until LogiGSK is started and profile manually loaded.

Have a wonderful day!

**Comment by MohamadSaada** [comment]
@EricBergeron the profile should load automatically, when Ubuntu boots up, are reloading it by hand each time?

**Comment by EricBergeron** [comment]
Hello mr Saada,

Yes, I need to load LogiGSK and load my profile.  But only if the computer
is coming from a windows7 session.

If it is ubuntu rebooting , everything stays.

In the end it is not a big effort compared to the pain of that strolling
bright rainbow ;)

Many thanks again!

Eric

**Comment by MohamadSaada** [comment]
@EricBergeron if you use LogiGSK service you don't need to load the profile manually. It will do it automatically. And you can use animated effects with the service as well. Cheers.

**Comment by EricBergeron** [comment]
I know it should, but it does not start automatically with Ubuntu.  Perhaps
I am overdue for a general re-instal of my system along with the upgrade to
16.04?

anyhow, your work is impressive and appreciated, Logitech should send you a
big gift for your birthday :)
Have a wonderful day!





2017-10-02 10:47 GMT-04:00 MohamadSaada <notifications@github.com>:

**Comment by MohamadSaada** [comment]
@EricBergeron I have found out why the service is not loading the set profiles. I will fix it tonight. Please try and install the new version after I have submitted it, and let me know how it goes. Cheers.

**Comment by EricBergeron** [comment]
Hello Mohamad,

I wont be able to test before next week, but for sure I will let you know
how it went.

thank you again very much for your time!
have a wonderful week!

Eric

Le 11 oct. 2017 8:26 AM, "MohamadSaada" <notifications@github.com> a écrit :

@EricBergeron <https://github.com/ericbergeron> I have found out why the
service is not loading the set profiles. I will fix it tonight. Please try
and install the new version after I have submitted it, and let me know how
it goes. Cheers.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/MohamadSaada/LogiGSK/issues/8#issuecomment-335792777>,
or mute the thread
