### ISSUE TITLE
Stuck in Loading Screen

### ISSUE THREAD

**Issue by sViech** [MohamadSaada/LogiGSK#9]
Hi, first of all: thanks for the work! 
I'm using Kubuntu 17.04 and the Logitech g910 orion spectrum.
I tried to build my own package and installed it - the program closed immediately after the start. 
With the Install script I'm getting so far that the program starts and shows loading but stays there - I'm able to click on "File" but the only thing I can click on is "Exit". When I click on "Edit" the entry "Settings" appears clickable but nothing happens when you click it.

**Comment by MohamadSaada** [comment]
@sViech Which version of Java are you using?

**Comment by sViech** [comment]
java --version --> 
openjdk version "9-Ubuntu"
OpenJDK Runtime Environment (build 9-Ubuntu+0-9b161-1)
OpenJDK 64-Bit Server VM (build 9-Ubuntu+0-9b161-1, mixed mode)

**Comment by MohamadSaada** [comment]
@sViech  yesterday I've installed Kubuntu 17.04, I did the following to create the package

`sudo apt-get install openjdk-8-jdk`
`sudo apt-get install ant`
`sudo apt-get install jsvc`
`sudo bash logigsk-buildpackage deb`

I then installed the deb file and everything worked fine, please try and make sure you have the full jdk installed. Or try the steps I did and check if it works. Cheers.

**Comment by sViech** [comment]
Sorry for my late reply, had lots of work to do.
Your solution brought no success but I then I had an idea.
I checked
`sudo update-alternatives --config java`
the result was
` * 0            /usr/lib/jvm/java-9-openjdk-amd64/bin/java       1091      automatischer Modus`
 ` 1            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manueller Modus`
 ` 2            /usr/lib/jvm/java-9-openjdk-amd64/bin/java       1091      manueller Modus`
I changed it to java-8 and it worked immediatly.
Again, thanks for your work.

**Comment by MohamadSaada** [comment]
@sViech glad that you have solved the problem. Please make sure that you have used the latest source code, as some changes have been made after your first comment. I am going to close this issue, if you do face any other problems, please open a new issue.

Cheers

Mohamad
